// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/quxionglie/showdb/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/getColumns",
				Handler: getColumnsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/getDatabases",
				Handler: getDatabasesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/getTables",
				Handler: getTablesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/showCreateTable",
				Handler: showCreateTableHandler(serverCtx),
			},
		},
	)
}
